# Generated by Django 5.0.4 on 2024-05-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='password',
        ),
    ]
