# Generated by Django 5.0.4 on 2024-05-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_alter_order_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
