# Generated by Django 5.0.4 on 2024-05-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
