# Generated by Django 4.2.10 on 2024-05-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0016_topproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproduct',
            name='pid',
            field=models.IntegerField(default=1),
        ),
    ]
